language: python

python:
  - "2.6"
  - "2.7"

install:
  - pip install -r requirements_travis.txt
  - pip install -r requirements_test.txt

script:
  - coverage run --source plex -m py.test

after_success:
  - coveralls